import { notFound } from "next/navigation";
import { adminService,requireAdminPage } from "@/server/admin/context";
import { AdminError } from "@/server/admin/errors";
import { AdminForm } from "@/components/admin/AdminForms";
import { date,money,status } from "@/components/admin/AdminDisplay";
import { formatOrderNumber } from "@/server/commerce/policies";
import styles from "@/components/admin/admin.module.css";
export default async function Detail({params}: {params:Promise<{orderNumber:string}>}){await requireAdminPage();const {orderNumber}=await params;let order;try{order=await adminService.detail(orderNumber);}catch(error){if(error instanceof AdminError && error.status===404)notFound();throw error;}const next:Record<string,string>={PAID:"PREPARING",PREPARING:"SHIPPED",SHIPPED:"DELIVERED"};const expired=!!order.reservationExpiresAt && order.reservationExpiresAt<=new Date();return <><h1>{formatOrderNumber(order.number)}</h1><p>{date(order.createdAt)} · {status(order.status)}</p><div className={styles.detailGrid}>
 <section className={styles.section}><h2>CLIENTE</h2><p>{order.firstName} {order.lastName}</p><p>{order.email}</p><p>{order.phone}</p></section>
 <section className={styles.section}><h2>ENTREGA</h2><p>{order.province} · {order.city}</p><p>{order.address}</p><h3>INSTRUCCIONES DEL CLIENTE</h3><p className={styles.pre}>{order.deliveryInstructions || "Sin instrucciones."}</p></section>
 <section className={styles.section}><h2>PRODUCTOS</h2>{order.items.map(item=><div className={styles.line} key={item.id}><strong>{item.productName} · {item.flavor}</strong><p>{item.quantity} × {money(item.unitPrice)} = {money(item.lineTotal)}</p></div>)}</section>
 <section className={styles.section}><h2>IMPORTES HISTÓRICOS</h2><p>Subtotal: {money(order.subtotal)}</p><p>Envío: {status(order.shippingMode)} · {order.shippingAmount===null ? "Importe desconocido, pagado al recibir" : money(order.shippingAmount)}</p><p>Total: <strong>{money(order.total)}</strong></p></section>
 <section className={styles.section}><h2>PAGO</h2>{order.payments.map(payment=><div key={payment.id}><p>{status(payment.method)} · {status(payment.status)}</p><p>Aviso del cliente: {date(payment.customerMarkedTransferredAt)}</p><p>Pago recibido: {date(payment.paidAt)}</p>{payment.provider && <p>{payment.provider} · {payment.providerReference}</p>}</div>)}<p>Reserva: {order.reservationStatus} · vence {date(order.reservationExpiresAt)}</p>{order.status==="PENDING_PAYMENT" && order.reservationStatus==="RESERVED" && !expired && <AdminForm action="confirm" label="CONFIRMAR PAGO RECIBIDO" confirmMessage={`¿Has comprobado que recibiste ${money(order.total)} para ${formatOrderNumber(order.number)}? El aviso del cliente no confirma el pago.`}><input type="hidden" name="id" value={order.id}/></AdminForm>}{expired && order.reservationStatus==="RESERVED" && <p className={styles.notice}>RESERVA VENCIDA. Revisa antes de aceptar una transferencia tardía; este flujo no la confirma automáticamente.</p>}{order.status==="PENDING_PAYMENT" && order.reservationStatus==="RESERVED" && <AdminForm action="cancel" label="CANCELAR PEDIDO Y LIBERAR RESERVA" confirmMessage="¿Cancelar este pedido impagado y liberar sus unidades reservadas? No es un reembolso." ><input type="hidden" name="id" value={order.id}/><label>Motivo<input name="reason" required maxLength={500}/></label></AdminForm>}{["PAID","PREPARING","SHIPPED","DELIVERED"].includes(order.status) && <p className={styles.help}>La devolución de pedidos pagados requiere un flujo de reembolso aún no implementado.</p>}</section>
 <section className={styles.section}><h2>PREPARACIÓN Y ENVÍO</h2><p>Transportista: {order.carrier || "—"}</p><p>Seguimiento: {order.trackingNumber || "—"}</p><p>Enviado: {date(order.shippedAt)}</p><p>Entregado: {date(order.deliveredAt)}</p>{next[order.status] && <AdminForm action="transition" label={`MARCAR ${status(next[order.status])}`} confirmMessage={`¿Cambiar a ${status(next[order.status])}?`}><input type="hidden" name="id" value={order.id}/><input type="hidden" name="status" value={next[order.status]}/>{order.status==="PREPARING" && <><label>Transportista<input name="carrier" required maxLength={100}/></label><label>Número de seguimiento<input name="trackingNumber" required maxLength={100}/></label></>}</AdminForm>}</section>
 </div><section className={styles.section}><h2>NOTAS INTERNAS · SOLO ADMIN</h2><AdminForm action="note" label="AÑADIR NOTA PRIVADA"><input type="hidden" name="id" value={order.id}/><label>Nota<textarea name="content" required maxLength={2000} rows={3}/></label></AdminForm>{order.notes.map(note=><article className={styles.line} key={note.id}><p className={styles.pre}>{note.content}</p><small>{note.author?.name ?? note.author?.email ?? "Sistema"} · {date(note.createdAt)}</small></article>)}<p className={styles.help}>Se muestran las últimas {order.notes.length} de {order._count.notes} notas; no se editan ni se incluyen en exportaciones.</p></section><section className={styles.section}><h2>HISTORIAL DE INVENTARIO</h2>{order.items.flatMap(item=>item.inventoryMovements.map(movement=><p key={movement.id}>{date(movement.createdAt)} · {item.flavor} · {movement.type} · Δ {movement.delta} · stock disponible {movement.stockAfter}</p>))}</section></>;}
