ALTER TYPE "InventoryMovementType" ADD VALUE 'RESERVATION';
ALTER TYPE "InventoryMovementType" ADD VALUE 'RESERVATION_CONFIRMED';
ALTER TYPE "InventoryMovementType" ADD VALUE 'RESERVATION_RELEASED';
CREATE TYPE "ReservationStatus" AS ENUM ('NONE', 'RESERVED', 'CONFIRMED', 'RELEASED');
