import Link from "next/link";
import { formatMoney,formatOrderNumber } from "@/server/commerce/policies";
import { Prisma } from "@/generated/prisma/client";
import type { createAdminService, Filters } from "@/server/admin/service";
import styles from "./admin.module.css";
export const labels:Record<string,string>={PENDING_PAYMENT:"PENDIENTE DE PAGO",PAID:"PAGADO",PREPARING:"EN PREPARACIÓN",SHIPPED:"ENVIADO",DELIVERED:"ENTREGADO",CANCELLED:"CANCELADO",REFUNDED:"REEMBOLSADO",PENDING:"PENDIENTE",FAILED:"FALLIDO",BANK_TRANSFER:"TRANSFERENCIA",CARD:"TARJETA",FREE:"GRATIS",PAY_ON_DELIVERY:"PAGADO AL RECIBIR"};
export const date=(value:Date|null|undefined)=>value ? new Intl.DateTimeFormat("es-EC",{timeZone:"America/Guayaquil",dateStyle:"medium",timeStyle:"short"}).format(value) : "—";
export const money=(value:Prisma.Decimal|null|undefined)=>formatMoney(value ?? new Prisma.Decimal(0),"USD");
export const status=(value:string)=>labels[value] ?? value;
type OrderRows=Awaited<ReturnType<ReturnType<typeof createAdminService>["listOrders"]>>["orders"];
export function OrdersTable({orders}: {orders:OrderRows}){if(!orders.length)return <p className={styles.empty}>NO HAY PEDIDOS PARA ESTOS FILTROS.</p>;return <div className={styles.tableWrap}><table><thead><tr>{["Pedido / Fecha","Cliente","Total","Pago","Estado","Transferencia","Zona"].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{orders.map(order=><tr key={order.id}><td><Link href={`/admin/pedidos/${formatOrderNumber(order.number)}`}>{formatOrderNumber(order.number)} ↗</Link><small>{date(order.createdAt)}</small></td><td>{order.firstName} {order.lastName}</td><td>{money(order.total)}</td><td>{order.payments.map((p,i)=><small key={i}>{status(p.method)} · {status(p.status)}</small>)}</td><td>{status(order.status)}</td><td>{order.payments.some(p=>p.customerMarkedTransferredAt) ? "AVISADA POR CLIENTE" : "SIN AVISO"}</td><td>{order.city}</td></tr>)}</tbody></table></div>;}
export function Pagination({page,count,base,filters}: {page:number;count:number;base:string;filters:Filters}){const url=(next:number)=>{const params=new URLSearchParams(Object.entries({...filters,page:String(next)}).filter(([,value])=>!!value) as [string,string][]);return `${base}?${params}`;};return <nav className={styles.pagination} aria-label="Paginación">{page>1 && <Link href={url(page-1)}>← ANTERIOR</Link>}<span>Página {page} · {count} resultados</span>{page*25<count && <Link href={url(page+1)}>SIGUIENTE →</Link>}</nav>;}
export function DateFilter({filters}: {filters:Filters}){return <form className={styles.filters}><label>Desde<input type="date" name="from" defaultValue={filters.from}/></label><label>Hasta<input type="date" name="to" defaultValue={filters.to}/></label><button className={styles.button}>FILTRAR</button></form>;}
export function SalesMetrics({metrics}: {metrics:Awaited<ReturnType<ReturnType<typeof createAdminService>["sales"]>>}){return <><div className={styles.metrics}>{[["Ingresos del periodo",money(metrics.all._sum.total)],["Ingresos hoy",money(metrics.today._sum.total)],["Ingresos esta semana",money(metrics.week._sum.total)],["Ingresos este mes",money(metrics.month._sum.total)],["Pedidos pagados hoy",metrics.today._count._all],["Pedidos pagados esta semana",metrics.week._count._all],["Pedidos pagados este mes",metrics.month._count._all],["Unidades vendidas",metrics.units],["Ticket promedio",money(metrics.all._avg.total)]].map(([label,value])=><div className={styles.metric} key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div><div className={styles.metrics}>{["LIMÓN","MANDARINA"].map(flavor=><div key={flavor} className={styles.metric}><span>Unidades {flavor}</span><strong>{metrics.flavors.find(row=>row.flavor===flavor)?._sum.quantity ?? 0}</strong></div>)}</div></>;}
